return {
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    events = { "VeryLazy" },
    dependencies = {
      "mason-org/mason.nvim",
    },
    opts = {
      "lua_ls",
      "angularls",
      "cssls",
      "docker_compose_language_service",
      "dockerls",
      "eslint",
      "gh_actions_ls",
      "gradle_ls",
      "html",
      "jdtls",
      "jsonls",
      "markdown_oxide",
      "mardownlint",
      "rust_analyzer",
      "sqlls",
      "tailwindcss",
      "texlab",
      "ts_ls",
      "yamlls",
    },
  },
}
